name: Hello world

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: windows-latest

    steps:
      - name: Print a message
        run: echo Hello from GitHub Actions

      - name: Show the date
        run: echo Today is %DATE%

      - name: Show which folder you are inside
        run: cd